## Challenge 2: Sets

There are a lot to learn about Python Sets and the information presented in the lesson is limited due to its length. To learn Python Sets in depth you are strongly encouraged to review the W3Schools tutorial on [Python Sets Examples and Methods](https://www.w3schools.com/python/python_sets.asp) before you work on this lab. Some difficult questions in this lab have their solutions in the W3Schools tutorial.

#### First, import the Python `random` library.

In [115]:
import random

#### In the cell below, create a list named `sample_list_1` with 80 random values. 

Requirements:

* Each value is an integer falling between 0 and 100.
* Each value in the list is unique.

Print `sample_list_1` to review its values

*Hint: use `random.sample` ([reference](https://docs.python.org/3/library/random.html#random.sample)).*

In [116]:
sample_list_1 = []

while len(sample_list_1) <= 79:
    num = random.randint(0,100)
    if num in sample_list_1:
        continue
    else:
        sample_list_1.append(num)
print(sample_list_1)

[65, 2, 38, 68, 91, 71, 95, 35, 7, 61, 92, 27, 82, 86, 36, 100, 34, 83, 70, 77, 81, 0, 96, 72, 31, 17, 28, 30, 67, 37, 4, 99, 62, 53, 60, 26, 57, 44, 69, 49, 25, 8, 89, 5, 48, 80, 3, 84, 88, 18, 11, 21, 52, 98, 64, 14, 66, 12, 42, 33, 63, 50, 9, 79, 16, 85, 58, 40, 32, 87, 75, 74, 94, 97, 55, 78, 59, 20, 15, 45]

#### Convert `sample_list_1` to a set called `set1`. Print the length of the set. Is its length still 80?

In [117]:
set1 = set(sample_list_1)
len(set1)

80

#### Create another list named `sample_list_2` with 80 random values.

Requirements:

* Each value is an integer falling between 0 and 100.
* The values in the list don't have to be unique.

*Hint: Use a FOR loop and the `randrange()` function.*

In [118]:
sample_list_2 = []

while len(sample_list_2) <= 79: 
    sample_list_2.append(random.randrange(0,101))
    
print(sample_list_2)

[59, 81, 97, 26, 15, 6, 18, 25, 79, 4, 57, 40, 99, 54, 9, 51, 23, 100, 25, 36, 31, 77, 22, 28, 77, 54, 90, 13, 91, 35, 17, 74, 26, 72, 77, 67, 74, 52, 11, 33, 71, 27, 49, 74, 91, 64, 99, 65, 16, 21, 3, 16, 25, 38, 62, 1, 62, 71, 30, 43, 86, 48, 30, 5, 19, 3, 3, 19, 1, 5, 81, 46, 9, 96, 32, 67, 10, 87, 13, 80]

#### Convert `sample_list_2` to a set called `set2`. Print the length of the set. Is its length still 80?

In [119]:
# Your code here
set2 = set(sample_list_2)
len(set2) 
#No, it is not 80, since there are repeated numbers.

57

#### Identify the elements present in `set1` but not in `set2`. Assign the elements to a new set named `set3`.

In [120]:
# Your code here
set3 = set1 - set2
print(set3)

{0, 2, 7, 8, 12, 14, 20, 34, 37, 42, 44, 45, 50, 53, 55, 58, 60, 61, 63, 66, 68, 69, 70, 75, 78, 82, 83, 84, 85, 88, 89, 92, 94, 95, 98}

#### Identify the elements present in `set2` but not in `set1`. Assign the elements to a new set named `set4`.

In [121]:
# Your code here
set4 = set2 - set1
print(set4)
len(set4)

{1, 6, 10, 43, 13, 46, 19, 51, 22, 23, 54, 90}

12

#### Now Identify the elements shared between `set1` and `set2`. Assign the elements to a new set named `set5`.

In [122]:
# Your code here
set5 = set1 & set2
print(set5)
set1.intersection(set2)

{3, 4, 5, 9, 11, 15, 16, 17, 18, 21, 25, 26, 27, 28, 30, 31, 32, 33, 35, 36, 38, 40, 48, 49, 52, 57, 59, 62, 64, 65, 67, 71, 72, 74, 77, 79, 80, 81, 86, 87, 91, 96, 97, 99, 100}

{3,
 4,
 5,
 9,
 11,
 15,
 16,
 17,
 18,
 21,
 25,
 26,
 27,
 28,
 30,
 31,
 32,
 33,
 35,
 36,
 38,
 40,
 48,
 49,
 52,
 57,
 59,
 62,
 64,
 65,
 67,
 71,
 72,
 74,
 77,
 79,
 80,
 81,
 86,
 87,
 91,
 96,
 97,
 99,
 100}

#### What is the relationship among the following values:

* len(set1)
* len(set2)
* len(set3)
* len(set4)
* len(set5)

Think about the set operations that you used to create the sets and how the lengths of the sets are related to each other given those operations.

In [123]:
# Your code here
#len(set5) == len(set1) + len(set2)
#len(set3) == len(set1) + len(set2)
#len(set3) == len(set5)
#len(set3) + len(set4) == len(set1)
len(set2) == len(set3) + len(set4)

False

#### Create an empty set called `set6`.

In [124]:
# Your code here
set6 = set()

#### Add `set3` and `set5` to `set6` using the Python Set `update` method.

In [125]:
# Your code here
set6.update(set3, set5)
print(set6)

{0, 2, 3, 4, 5, 7, 8, 9, 11, 12, 14, 15, 16, 17, 18, 20, 21, 25, 26, 27, 28, 30, 31, 32, 33, 34, 35, 36, 37, 38, 40, 42, 44, 45, 48, 49, 50, 52, 53, 55, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 91, 92, 94, 95, 96, 97, 98, 99, 100}

#### Check if `set1` and `set6` are equal.

In [126]:
# Your code here
set1 == set6

True

#### Check if `set1` contains `set2` using the Python Set `issubset` method. Then check if `set1` contains `set3`.

In [127]:
# Your code here
set1.issubset(set2)

False

#### Using the Python Set `union` method, aggregate `set3`, `set4`, and `set5`. Then aggregate `set1` and `set2`. 

#### Check if the aggregated values are equal.

In [128]:
# Your code here
set345 = set3.union(set4, set5)
len(set345)
set12 = set1.union(set2)
len(set12)
set345 == set12

True

#### Using the `pop` method, remove the first element from `set1`.

In [129]:
# Your code here
set1modify = set1.pop()
print(set1modify)

0

#### Remove every element in the following list from `set1` if they are present in the set. Print the remaining elements.

```
list_to_remove = [1, 9, 11, 19, 21, 29, 31, 39, 41, 49, 51, 59, 61, 69, 71, 79, 81, 89, 91, 99]
```

In [141]:
list_to_remove = [1, 9, 11, 19, 21, 29, 31, 39, 41, 49, 51, 59, 61, 69, 71, 79, 81, 89, 91, 99]

removed = set1.difference_update(list_to_remove)
print(set1)

{2, 3, 4, 5, 7, 8, 12, 14, 15, 16, 17, 18, 20, 25, 26, 27, 28, 30, 32, 33, 34, 35, 36, 37, 38, 40, 42, 44, 45, 48, 50, 52, 53, 55, 57, 58, 60, 62, 63, 64, 65, 66, 67, 68, 70, 72, 74, 75, 77, 78, 80, 82, 83, 84, 85, 86, 87, 88, 92, 94, 95, 96, 97, 98, 100}